### ISSUE TITLE
Feature Suggestion

### ISSUE THREAD

**Issue by 256Laika** [Flairwars/tillicev2#46]
256Axel

argument starter command (obviously just lighthearted stuff), the bot says a controversial statement that is intended to start a discussion, like ~topic or ~wyr. People could suggest argument starters with a system similar to the one we have for topic suggestion.

It’s mainly just supposed to be a fun command that could work as an alternative to ~topic for more variety, lighthearted argument in gen are usually pretty fun so yeah uhh.

**Comment by ghost** [comment]
The new `~topic` command can be invoked like `~topic [subreddit]` for any sfw subreddit. This functionality is already in place with possible commands like `~topic wouldyourather` and `~topic the10thdentist`.
